%% This function will replace the binary data in a given DICOM folder with
% the data which you have tampered with.&
%
% 
%  Author: Lalith Kumar Shiyam Sundar, M.Sc.
%  Date: Feb 15th, 2017
%  Quantitative Imaging and Medical Physics, Medical University of Vienna.
%
%-------------------------------------------------------------------------%
%                              Program start
%-------------------------------------------------------------------------%

function []=pushDataToDicom(DicomPath,niftyVolume)
cd(DicomPath);
dicomImages=dir;
dicomImages=dicomImages(arrayfun(@(x) x.name(1), dicomImages) ~= '.'); 
niftyVolume=rot90(niftyVolume,2);
niftyVolume=flipdim(niftyVolume,1);
h = cProgress ( 0, 'Loading images'); % intializing the progressbar.
% get rows and columns

for lp=1:length(dicomImages)
    cProgress(100.*(lp/length(dicomImages)),h) % fancy progressbar runs - you are welcome.
    info = dicominfo(dicomImages(lp).name); % read the whole file size of a single size
    rowsInfo=double(info.Rows);columnsInfo=double(info.Columns);
    ImpInfo=ReadDicomElementList(dicomImages(lp).name); % store the structs which are generated by dicomdisp
    fid=fopen(dicomImages(lp).name,'r+'); % open the file for reading
    OffSetData=info.FileSize-ImpInfo(end).location; 
    %OffSetData=0;
    status=fseek(fid,-(OffSetData+(rowsInfo*columnsInfo*2)),'eof'); % always go from 'end of the file', place the cursor where the pixel data starts, including the offset
    % find out where the pixel data really ends, works for siemens.
    A=niftyVolume(:,:,info.InstanceNumber); % get the corresponding CT uMap slice based on the instance number.
    count=fwrite(fid,A(:),'uint16'); % write the CT uMap to the MR uMap slices.
    fclose(fid); % always close the file.
end
close(h);
end
